// Generated by demo/dm1_missing_text_export.py -- do not hand-edit.
// Exact word/sign location of each packet's gap, computed from
// Phase1_pipeline/p4_out/decomposed_corpus.parquet (now carrying a
// word_index_in_line column added specifically for this alignment --
// see lib/decompose_corpus.py). Every entry here was verified by
// reproducing the packet's own left_context/right_context tokens
// exactly; packets that didn't reconcile are simply absent (the
// fragment panel falls back to line-only highlighting for those).
const TAKSAN_GAP_LOCATIONS = {
  "p2e4-001": {
    "line_index_in_doc": 13,
    "word_indices": [
      5
    ],
    "words": [
      {
        "word_index_in_line": 5,
        "tokens": [
          {
            "token": "URU",
            "damage_state": "laes",
            "is_gap": false
          },
          {
            "token": "iš",
            "damage_state": "laes",
            "is_gap": false
          },
          {
            "token": "da",
            "damage_state": "laes",
            "is_gap": true
          },
          {
            "token": "ḫa",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "ra",
            "damage_state": "attested",
            "is_gap": false
          }
        ]
      }
    ]
  },
  "p2e4-002": {
    "line_index_in_doc": 78,
    "word_indices": [
      1
    ],
    "words": [
      {
        "word_index_in_line": 1,
        "tokens": [
          {
            "token": "na",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "an",
            "damage_state": "attested",
            "is_gap": true
          }
        ]
      }
    ]
  },
  "p2e4-003": {
    "line_index_in_doc": 3,
    "word_indices": [
      2
    ],
    "words": [
      {
        "word_index_in_line": 2,
        "tokens": [
          {
            "token": "pí",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "an",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "zi",
            "damage_state": "attested",
            "is_gap": false
          }
        ]
      }
    ]
  },
  "p2e4-004": {
    "line_index_in_doc": 29,
    "word_indices": [
      1
    ],
    "words": [
      {
        "word_index_in_line": 1,
        "tokens": [
          {
            "token": "〈",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "LÚ",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "MEŠ",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "〉˽",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "GIŠ",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "BANŠUR",
            "damage_state": "attested",
            "is_gap": false
          }
        ]
      }
    ]
  },
  "p2e4-005": {
    "line_index_in_doc": 11,
    "word_indices": [
      3
    ],
    "words": [
      {
        "word_index_in_line": 3,
        "tokens": [
          {
            "token": "A",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "NA",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "KARAŠ",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "ḪI",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "A",
            "damage_state": "laes",
            "is_gap": false
          }
        ]
      }
    ]
  },
  "p2e4-006": {
    "line_index_in_doc": 12,
    "word_indices": [
      3
    ],
    "words": [
      {
        "word_index_in_line": 3,
        "tokens": [
          {
            "token": "A",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "NA",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "m",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "a",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "bi",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "rad",
            "damage_state": "restored",
            "is_gap": false
          },
          {
            "token": "da",
            "damage_state": "attested",
            "is_gap": false
          }
        ]
      }
    ]
  },
  "p2e4-007": {
    "line_index_in_doc": 75,
    "word_indices": [
      6
    ],
    "words": [
      {
        "word_index_in_line": 6,
        "tokens": [
          {
            "token": "na",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "at",
            "damage_state": "restored",
            "is_gap": false
          },
          {
            "token": "za",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "kán",
            "damage_state": "attested",
            "is_gap": false
          }
        ]
      }
    ]
  },
  "p2e4-008": {
    "line_index_in_doc": 13,
    "word_indices": [
      0
    ],
    "words": [
      {
        "word_index_in_line": 0,
        "tokens": [
          {
            "token": "ma",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "a",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "an",
            "damage_state": "attested",
            "is_gap": true
          }
        ]
      }
    ]
  },
  "p2e4-009": {
    "line_index_in_doc": 7,
    "word_indices": [
      3
    ],
    "words": [
      {
        "word_index_in_line": 3,
        "tokens": [
          {
            "token": "pé",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "e",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "ḫu",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "da",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "an",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "zi",
            "damage_state": "attested",
            "is_gap": false
          }
        ]
      }
    ]
  },
  "p2e4-010": {
    "line_index_in_doc": 19,
    "word_indices": [
      5
    ],
    "words": [
      {
        "word_index_in_line": 5,
        "tokens": [
          {
            "token": "LÚ",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "MEŠ",
            "damage_state": "attested",
            "is_gap": true
          }
        ]
      }
    ]
  },
  "p2e4-011": {
    "line_index_in_doc": 24,
    "word_indices": [
      4
    ],
    "words": [
      {
        "word_index_in_line": 4,
        "tokens": [
          {
            "token": "D",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "mu",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "ú",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "ki",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "ša",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "nu",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "un",
            "damage_state": "attested",
            "is_gap": false
          }
        ]
      }
    ]
  },
  "p2e4-012": {
    "line_index_in_doc": 8,
    "word_indices": [
      0
    ],
    "words": [
      {
        "word_index_in_line": 0,
        "tokens": [
          {
            "token": "nu",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "uš",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "ma",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "aš",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "kán",
            "damage_state": "attested",
            "is_gap": true
          }
        ]
      }
    ]
  },
  "p2e4-013": {
    "line_index_in_doc": 27,
    "word_indices": [
      4
    ],
    "words": [
      {
        "word_index_in_line": 4,
        "tokens": [
          {
            "token": "A",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "BI",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "IA",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "ma",
            "damage_state": "attested",
            "is_gap": false
          }
        ]
      }
    ]
  },
  "p2e4-014": {
    "line_index_in_doc": 35,
    "word_indices": [
      2
    ],
    "words": [
      {
        "word_index_in_line": 2,
        "tokens": [
          {
            "token": "pal",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "u",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "wa",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "ez",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "zi",
            "damage_state": "attested",
            "is_gap": false
          }
        ]
      }
    ]
  },
  "p2e4-015": {
    "line_index_in_doc": 29,
    "word_indices": [
      1
    ],
    "words": [
      {
        "word_index_in_line": 1,
        "tokens": [
          {
            "token": "ḫa",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "an",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "te",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "ez",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "zi",
            "damage_state": "restored",
            "is_gap": false
          }
        ]
      }
    ]
  },
  "p2e4-016": {
    "line_index_in_doc": 63,
    "word_indices": [
      1
    ],
    "words": [
      {
        "word_index_in_line": 1,
        "tokens": [
          {
            "token": "NINDA",
            "damage_state": "restored",
            "is_gap": false
          },
          {
            "token": "tu",
            "damage_state": "restored",
            "is_gap": false
          },
          {
            "token": "ḫu",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "ra",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "i",
            "damage_state": "attested",
            "is_gap": true
          }
        ]
      }
    ]
  },
  "p2e6-001": {
    "line_index_in_doc": 5,
    "word_indices": [
      2,
      3
    ],
    "words": [
      {
        "word_index_in_line": 2,
        "tokens": [
          {
            "token": "BE",
            "damage_state": "restored",
            "is_gap": false
          },
          {
            "token": "LÍ",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "NI",
            "damage_state": "attested",
            "is_gap": true
          }
        ]
      },
      {
        "word_index_in_line": 3,
        "tokens": [
          {
            "token": "ku",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "iš",
            "damage_state": "laes",
            "is_gap": false
          }
        ]
      }
    ]
  },
  "p2e6-002": {
    "line_index_in_doc": 4,
    "word_indices": [
      2
    ],
    "words": [
      {
        "word_index_in_line": 2,
        "tokens": [
          {
            "token": "ma",
            "damage_state": "restored",
            "is_gap": false
          },
          {
            "token": "a",
            "damage_state": "restored",
            "is_gap": false
          },
          {
            "token": "an",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "wa",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "an",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "na",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "aš",
            "damage_state": "attested",
            "is_gap": false
          }
        ]
      }
    ]
  },
  "p2e6-003": {
    "line_index_in_doc": 4,
    "word_indices": [
      3,
      4
    ],
    "words": [
      {
        "word_index_in_line": 3,
        "tokens": [
          {
            "token": "NAM",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "RA",
            "damage_state": "attested",
            "is_gap": true
          }
        ]
      },
      {
        "word_index_in_line": 4,
        "tokens": [
          {
            "token": "GU₄",
            "damage_state": "attested",
            "is_gap": true
          }
        ]
      }
    ]
  },
  "p2e6-004": {
    "line_index_in_doc": 2,
    "word_indices": [
      3
    ],
    "words": [
      {
        "word_index_in_line": 3,
        "tokens": [
          {
            "token": "M",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "te",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "li",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "pí",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "nu",
            "damage_state": "attested",
            "is_gap": false
          }
        ]
      }
    ]
  },
  "p2e6-005": {
    "line_index_in_doc": 4,
    "word_indices": [
      2
    ],
    "words": [
      {
        "word_index_in_line": 2,
        "tokens": [
          {
            "token": "ma",
            "damage_state": "restored",
            "is_gap": false
          },
          {
            "token": "a",
            "damage_state": "restored",
            "is_gap": false
          },
          {
            "token": "an",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "wa",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "an",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "na",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "aš",
            "damage_state": "attested",
            "is_gap": false
          }
        ]
      }
    ]
  },
  "p2e6-006": {
    "line_index_in_doc": 20,
    "word_indices": [
      3,
      4
    ],
    "words": [
      {
        "word_index_in_line": 3,
        "tokens": [
          {
            "token": "na",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "at",
            "damage_state": "attested",
            "is_gap": true
          }
        ]
      },
      {
        "word_index_in_line": 4,
        "tokens": [
          {
            "token": "EGIR",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "pa",
            "damage_state": "attested",
            "is_gap": false
          }
        ]
      }
    ]
  },
  "p2e6-007": {
    "line_index_in_doc": 3,
    "word_indices": [
      3
    ],
    "words": [
      {
        "word_index_in_line": 3,
        "tokens": [
          {
            "token": "F",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "ḫa",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "ra",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "ap",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "ši",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "ti",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "en",
            "damage_state": "laes",
            "is_gap": false
          }
        ]
      }
    ]
  },
  "p2e6-008": {
    "line_index_in_doc": 2,
    "word_indices": [
      3
    ],
    "words": [
      {
        "word_index_in_line": 3,
        "tokens": [
          {
            "token": "M",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "te",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "li",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "pí",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "nu",
            "damage_state": "attested",
            "is_gap": false
          }
        ]
      }
    ]
  },
  "p2e6-009": {
    "line_index_in_doc": 2,
    "word_indices": [
      3,
      4,
      5
    ],
    "words": [
      {
        "word_index_in_line": 3,
        "tokens": [
          {
            "token": "LI",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "IM",
            "damage_state": "attested",
            "is_gap": true
          }
        ]
      },
      {
        "word_index_in_line": 4,
        "tokens": [
          {
            "token": "<NUM>",
            "damage_state": "attested",
            "is_gap": true
          }
        ]
      },
      {
        "word_index_in_line": 5,
        "tokens": [
          {
            "token": "ME",
            "damage_state": "laes",
            "is_gap": true
          }
        ]
      }
    ]
  },
  "p2e6-010": {
    "line_index_in_doc": 3,
    "word_indices": [
      3
    ],
    "words": [
      {
        "word_index_in_line": 3,
        "tokens": [
          {
            "token": "F",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "ḫa",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "ra",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "ap",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "ši",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "ti",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "en",
            "damage_state": "laes",
            "is_gap": false
          }
        ]
      }
    ]
  },
  "p2e6-011": {
    "line_index_in_doc": 17,
    "word_indices": [
      2,
      3,
      4
    ],
    "words": [
      {
        "word_index_in_line": 2,
        "tokens": [
          {
            "token": "M",
            "damage_state": "restored",
            "is_gap": false
          },
          {
            "token": "du",
            "damage_state": "restored",
            "is_gap": false
          },
          {
            "token": "ut",
            "damage_state": "restored",
            "is_gap": false
          },
          {
            "token": "ḫa",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "li",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "ia",
            "damage_state": "attested",
            "is_gap": true
          }
        ]
      },
      {
        "word_index_in_line": 3,
        "tokens": [
          {
            "token": "A",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "BI",
            "damage_state": "attested",
            "is_gap": true
          }
        ]
      },
      {
        "word_index_in_line": 4,
        "tokens": [
          {
            "token": "A",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "BI",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "IA",
            "damage_state": "restored",
            "is_gap": false
          }
        ]
      }
    ]
  },
  "p2e6-012": {
    "line_index_in_doc": 7,
    "word_indices": [
      5
    ],
    "words": [
      {
        "word_index_in_line": 5,
        "tokens": [
          {
            "token": "za",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "aḫ",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "ḫi",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "ia",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "u",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "wa",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "aš",
            "damage_state": "attested",
            "is_gap": true
          },
          {
            "token": "ta",
            "damage_state": "attested",
            "is_gap": false
          },
          {
            "token": "ti",
            "damage_state": "attested",
            "is_gap": false
          }
        ]
      }
    ]
  }
};
