#!/usr/bin/env python3
"""Stamp reports whose numbers predate the P4-D language projection.

P4-D changed what the active P2-E and real-gap scripts compute, but no metric
artifact was rerun -- that is P4-G work, gated behind the charter. The
committed reports therefore no longer match the code that produced them.

Rather than leave that divergence implicit (a future session would read a
committed number as current), each affected report carries a note naming the
change and the measured direction. The stamp is scripted, not hand-edited, so
the affected set is auditable and the action is reproducible; it is idempotent
and disappears naturally when a report is regenerated by its own script.

Usage:
    python scripts/p4d_stamp_stale_reports.py
    python scripts/p4d_stamp_stale_reports.py --check   # CI-friendly, no write
"""
import argparse
import sys
from pathlib import Path

MARKER = "<!-- p4d-staleness-stamp -->"

WITNESS_INDEX_NOTE = """{marker}
> **[PREDATES P4-D — numbers not recomputed]** This report was produced under
> the pre-Phase-4 line-granularity Hittite filter. P4-D (2026-07-26) replaced
> it with a required, word-aware language scope
> (`reports/phase4_p4d_language_aware_apis.md`). On the measured real-gap
> slice the word-aware projection refuses **932 lines** the line-granularity
> filter admitted — `Hit`-tagged lines carrying explicit non-Hittite words —
> reducing witness-index tokens by ~6.1%. The direction of the effect on this
> report's figures is therefore known but its magnitude is not; the numbers
> below have **not** been recomputed. Rerunning is P4-G work.
"""

QUERY_SIDE_NOTE = """{marker}
> **[PREDATES P4-D — numbers not recomputed]** This report was produced before
> the real-gap query side was language-resolved. Under P4-D (2026-07-26) a gap
> may only ASK under the same explicit language scope that governs which
> witness lines may ANSWER; previously every line in the slice could query,
> so non-Hittite gaps sat in the same denominator and simply found no
> coverage. On the measured slice **~9.5% of the gap population** was
> non-Hittite or unresolved. The witness index was also rebuilt word-aware
> (932 previously-admitted lines now refused). The numbers below have **not**
> been recomputed; rerunning is P4-G work. See
> `reports/phase4_p4d_language_aware_apis.md`.
"""

CENSUS_NOTE = """{marker}
> **[LANGUAGE-BLIND POPULATION — read with P4-D in mind]** This census counts
> real gaps without any language filter, which remains a correct description
> of the corpus. Downstream steps now scope queries explicitly (P4-D,
> 2026-07-26): on the witness-check slice ~9.5% of this population is
> non-Hittite or unresolved-language and is excluded from Hittite-only
> coverage figures. This report's own counts are unaffected and were not
> recomputed. See `reports/phase4_p4d_language_aware_apis.md`.
"""

# Reports still carrying pre-P4-D numbers. `--check` runs in CI, so a stamp
# cannot be quietly deleted.
#
# REMOVAL PROTOCOL: a target leaves this list only when its own script has
# actually been rerun under the P4-D projection, in the same change that
# removes it. Regeneration drops the stamp naturally, so an entry left here
# after a legitimate rerun would fail CI -- that is the intended coupling, not
# a bug. Moving an entry to RERUN_UNDER_P4D records that it happened.
# Rerun under the P4-D projection on 2026-07-27 (P4-G). These must NOT carry
# the stamp any more: their numbers are current, so the note would itself be
# the false claim.
RERUN_UNDER_P4D = [
    "reports/phase2_p2e_witness_recoverability.md",
    "reports/phase2_p2e2_abstention_calibration.md",
    "reports/phase2_p2e3_cross_calibration.md",
    "reports/phase2_p2e4_candidate_set_audit.md",
    "reports/phase2_p2e5_alignment_probe.md",
    "reports/phase2_p2e6_multisign_horizon.md",
    "Phase3/real_gaps_out/real_gap_witness_check_report.md",
    "Phase3/real_gaps_out/real_gap_calibration_report.md",
    "Phase3/real_gaps_out/real_gap_multisign_calibration_report.md",
]

TARGETS = [
    # The census was rerun too, but its caveat is NOT about staleness: the
    # census is a deliberately language-blind structural count, and its 181,051
    # runs are unchanged. Regenerating it stripped a note that is still true,
    # so it stays stamped until the census itself is language-stratified.
    ("Phase3/real_gaps_out/real_gap_census_report.md", CENSUS_NOTE),
]


def stamp(path, note, *, check):
    """Insert the note after the report's H1 title. Idempotent."""
    text = path.read_text(encoding="utf-8")
    if MARKER in text:
        return "already-stamped"
    if check:
        return "MISSING"

    lines = text.split("\n")
    insert_at = 0
    for index, line in enumerate(lines):
        if line.startswith("# "):
            insert_at = index + 1
            break
    body = note.format(marker=MARKER).rstrip("\n")
    lines[insert_at:insert_at] = ["", body]
    path.write_text("\n".join(lines), encoding="utf-8")
    return "stamped"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true",
        help="report unstamped targets without writing; exit 1 if any")
    args = parser.parse_args()

    missing = 0
    for relative, note in TARGETS:
        path = Path(relative)
        if not path.exists():
            print(f"  SKIP (absent)   {relative}")
            continue
        result = stamp(path, note, check=args.check)
        if result == "MISSING":
            missing += 1
        print(f"  {result:<15} {relative}")

    # The other half of the invariant: a report recorded as rerun must NOT
    # still carry a stamp, or the stamp is now itself the stale claim.
    contradicted = 0
    for relative in RERUN_UNDER_P4D:
        path = Path(relative)
        if path.exists() and MARKER in path.read_text(encoding="utf-8"):
            contradicted += 1
            print(f"  STAMPED-BUT-RERUN {relative}")

    if args.check and (missing or contradicted):
        if missing:
            print(f"\n{missing} report(s) lack the P4-D staleness stamp.")
        if contradicted:
            print(f"{contradicted} report(s) are recorded as rerun under P4-D "
                  "but still carry the staleness stamp.")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
